PandaProd updates for 009
PandaPhysics/PandaProd pull request #55
Opened 2018-01-25 20:37 UTC by DylanHsu

still working, needs more features and testing before merge

2018-01-25 21:39 UTC, DylanHsu commented
Ok, Electron MVA ID is working, thanks Yutaro for help with the EDAnalyzer sequence.

2018-01-29 22:25 UTC, DylanHsu commented
I've tested and added all of the quantities I think are needed for WH(bb) and Z(ll)H(bb). What else do we want in Panda009?

2018-01-30 02:06 UTC, sidnarayanan commented
I still need to add the tracking info. Give me a day to add it to PandaTree; I can add it to PandaProd later (won't affect the 009 production or data format).

2018-01-30 08:17 UTC, dabercro commented
Can you run `testpanda` over your output file and post the link here? It should already be in your `PATH` after compiling PandaTree.

2018-01-30 08:19 UTC, dabercro commented
Also, if we want to make the output easier for us to skim, we should merge https://github.com/PandaPhysics/PandaTree/pull/100 first. Are there any objections? @yiiyama @sidnarayanan @maierbenedikt

2018-01-30 14:24 UTC, DylanHsu commented
Running Dan's unit test/rel val thingy:
`testpanda /data/t3home000/dhsu/miniAOD/pandaSingleElectron1.root` -> `http://t3serv001.mit.edu/~dhsu/relval/?d=180130_092202`

Relevant plots for this PR:
http://t3serv001.mit.edu/~dhsu/relval/180130_092202/tracks/highPurity.png
http://t3serv001.mit.edu/~dhsu/relval/180130_092202/electrons/mvaVal.png
http://t3serv001.mit.edu/~dhsu/relval/180130_092202/electrons/mvaWP80.png
http://t3serv001.mit.edu/~dhsu/relval/180130_092202/electrons/mvaWP90.png
http://t3serv001.mit.edu/~dhsu/relval/180130_092202/common/pfMetSignificance.png

(This was cool, glad I know how to use it now.)

2018-01-30 14:41 UTC, dabercro commented
@DylanHsu Glad you liked it! The PR I made also includes some minor fixes. (Note how the metadata at the top has a silly file name.)

2018-01-30 15:09 UTC, dabercro requested changes

2018-01-30 15:09 UTC, dabercro commented on Producer/src/MetFiller.cc
> +    _outEvent.pfMetSignificance = patMet->metSignificance();
We should keep significance as a member of the MET. It's probably not a good idea to be writing to the global event in the MetFiller. If someone runs multiple fillers over a different kind of patMet, they'll overwrite each other, and you won't know which one actually filled the event.

2018-01-30 16:24 UTC, DylanHsu commented on Producer/src/MetFiller.cc
> +    _outEvent.pfMetSignificance = patMet->metSignificance();
There is only one pat::MET object in the event, MET significance is not well defined for any MET except PF MET, and MetFiller::fill is only designed to be called once.

2018-01-30 16:27 UTC, sidnarayanan commented on Producer/src/MetFiller.cc
> +    _outEvent.pfMetSignificance = patMet->metSignificance();
`MetFiller::fill` is called twice [1] per event. I agree with Dan. If you don't think it is well-defined for non-PF MET, then don't call the subroutine, but it should be a part of the MET class. 

[1] https://github.com/PandaPhysics/PandaProd/blob/master/Producer/python/panda_cfi.py#L283-L294

2018-01-30 16:32 UTC, DylanHsu commented on Producer/src/MetFiller.cc
> +    _outEvent.pfMetSignificance = patMet->metSignificance();
So the subroutine is just a getter, I was more concerned with saving extra bytes per event. I guess we can make it a property of panda::Met and save the output of pat::MET::metSignificance in the other panda::Met's regardless of what junk is saved in the miniAOD for that pat::MET.

2018-01-30 16:38 UTC, dabercro commented on Producer/src/MetFiller.cc
> +    _outEvent.pfMetSignificance = patMet->metSignificance();
Even if that were true, there's no reason to not make it a member of the MET object. Also, we're using MetFiller multiple times for PUPPI MET: https://github.com/PandaPhysics/PandaProd/blob/88f7aa0b95a5a5cc0fbe294772ff49d7adebfc3f/Producer/python/panda_cfi.py#L283-L294 I wouldn't be surprised if you're plot is actually PuppiMetSignificance.

Not making it a member of MET will require us to always only use MetFiller once. It's a sync nightmare waiting to happen. We should keep physics object robustness a high priority. Even being temporarily correct is not as good as good design.

It shouldn't be a hard fix. Just move the significance from `{Event}` to `[RecoMet]` and change the line to match the ones above it.

2018-01-30 16:39 UTC, sidnarayanan commented on Producer/src/MetFiller.cc
> +    _outEvent.pfMetSignificance = patMet->metSignificance();
If you're worried about the extra bytes, you can always drop the branch for puppi MET.

2018-01-30 16:40 UTC, sidnarayanan commented on Producer/src/MetFiller.cc
> +    _outEvent.pfMetSignificance = patMet->metSignificance();
e.g. `fillOthers` is only set to true for PF MET, so just add the significance here: https://github.com/PandaPhysics/PandaProd/blob/master/Producer/src/MetFiller.cc#L31

2018-01-30 16:44 UTC, dabercro commented on Producer/src/MetFiller.cc
> +    _outEvent.pfMetSignificance = patMet->metSignificance();
Oops, I didn't see Sid's comment. Is there really a need to drop it from PuppiMET? It seems like a very small cost to store something that might be useful.

2018-01-30 16:47 UTC, DylanHsu commented on Producer/src/MetFiller.cc
> +    _outEvent.pfMetSignificance = patMet->metSignificance();
Sure, we can keep it, and since it was overwriting, I guess the rel val plot above is actually showing that it is filled in miniAOD for puppiMET

2018-01-30 16:56 UTC, DylanHsu commented
the requested change is committed, running the unit test now

2018-01-30 17:39 UTC, DylanHsu commented
unit test complete
`http://t3serv001.mit.edu/~dhsu/relval/?d=180130_123702`

PF met significance has the expected properties now
http://t3serv001.mit.edu/~dhsu/relval/180130_123702/pfMet/significance.png

puppi met significance is also there:
http://t3serv001.mit.edu/~dhsu/relval/180130_123702/puppiMet/significance.png

2018-01-30 17:47 UTC, dabercro approved these changes

2018-01-30 17:47 UTC, dabercro commented
Nice, thanks!

2018-01-30 17:49 UTC, dabercro commented on Producer/src/MetFiller.cc
> +    _outEvent.pfMetSignificance = patMet->metSignificance();
Yeah, I was thinking none of us are really MET experts, so it would be safer to have.

2018-02-01 16:25 UTC, DylanHsu commented
Please merge

2018-02-01 16:33 UTC, merged